### ISSUE TITLE
Environment not properly specified.

### ISSUE THREAD

**Issue by Trezorro** [facebookresearch/flow_matching#21]
Trying to run the standalone flow matching notebook example results in an immediate error during import, given the specified conda environment in `environment.yml`.

<details><summary>environment.yml</summary>
<p>

```
name: flow_matching
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pytorch
  - matplotlib
  - jupyter
  - numpy
  - pip
  - tqdm
  - pip:
    - pre-commit
    - black==22.6.0
    - usort==1.0.4
    - ufmt==2.3.0
    - flake8==7.0.0
    - ipykernel
    - torchdiffeq
    - scikit-learn
    - pydoclint
    - coverage
```

</p>
</details> 

I followed instrunctions in the readme to recreate the environment, except I deleted `  - pytorch-cuda` from the yaml file (running on a non-cuda enabled macbook.)

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3048, in run_cell
    result = self._run_cell(
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3103, in _run_cell
    result = runner(coro)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3308, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3490, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/nd/9n52sjcx7fjgd3vb1wx3l9_c0000gn/T/ipykernel_96388/2746622047.py", line 1, in <module>
    import torch
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
[/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20](https://file+.vscode-resource.vscode-cdn.net/usr/local/Caskroom/miniconda/base/envs/flow_matching/lib/python3.9/site-packages/torch/nn/modules/transformer.py:20): UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at [/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1711403209812/work/torch/csrc/utils/tensor_numpy.cpp:84](https://file+.vscode-resource.vscode-cdn.net/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1711403209812/work/torch/csrc/utils/tensor_numpy.cpp:84).)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
```

In the last cell with matplotlib calls, I get:
`... RuntimeError: Numpy is not available`

The yaml file is not specific about most of the package versions, so I expect this won't be the last error I will encounter with this specification. 

P.S.: Only python is pinned to version 3.9. It is not clear to me why the package is pinned to this older version.

**Comment by mhavasi** [comment]
Hey @Trezorro ,

I tried reproducing your issue but I couldn't. Please try again with a fresh conda environment.

If the problem persists, please re-open the issue and include exact steps for reproduction.
